import Foundation
 
struct GamblingSite: Identifiable {
    let id = UUID()
    let name: String
    let domain: String
}
 
// Sites légaux agréés par l'ANJ (paris sportifs, hippiques, poker) — liste officielle complète
let knownGamblingSites: [GamblingSite] = [
    GamblingSite(name: "Winamax", domain: "winamax.fr"),
    GamblingSite(name: "Betclic", domain: "betclic.fr"),
    GamblingSite(name: "Unibet", domain: "unibet.fr"),
    GamblingSite(name: "PMU", domain: "pmu.fr"),
    GamblingSite(name: "Bwin", domain: "bwin.fr"),
    GamblingSite(name: "PartyPoker", domain: "partypoker.fr"),
    GamblingSite(name: "ZEturf", domain: "zeturf.fr"),
    GamblingSite(name: "NetBet", domain: "netbet.fr"),
    GamblingSite(name: "NetBet Sport", domain: "netbetsport.fr"),
    GamblingSite(name: "Bet365", domain: "bet365.fr"),
    GamblingSite(name: "Betsson", domain: "betsson.fr"),
    GamblingSite(name: "Olybet", domain: "olybet.fr"),
    GamblingSite(name: "CircusBet", domain: "circusbet.fr"),
    GamblingSite(name: "DAZNBet", domain: "daznbet.fr"),
    GamblingSite(name: "Genybet", domain: "genybet.fr"),
    GamblingSite(name: "Feelingbet", domain: "feelingbet.fr"),
    GamblingSite(name: "Yes or No", domain: "yesorno-jeu.fr"),
    GamblingSite(name: "VBet", domain: "vbet.fr"),
    GamblingSite(name: "PokerStars", domain: "pokerstars.fr")
]
 
// Casinos en ligne — tous interdits en France (l'ANJ ne délivre aucune licence casino).
// Liste issue de la "liste noire" officielle de l'ANJ (sites ayant fait l'objet d'un blocage administratif).
// Ces sites changent fréquemment de nom de domaine (sites miroirs) — liste à renouveler régulièrement.
let knownCasinoSites: [GamblingSite] = [
    GamblingSite(name: "MRSLOTY", domain: "mrsloty.com"),
    GamblingSite(name: "RICHPRIZE", domain: "richprize.com"),
    GamblingSite(name: "LUCYSCASINO", domain: "lucyscasino.com"),
    GamblingSite(name: "JUPICASINO", domain: "jupicasino.com"),
    GamblingSite(name: "LEROIJOHNNY", domain: "leroijohnny.com"),
    GamblingSite(name: "KAHUNACASINO", domain: "kahunacasino.com"),
    GamblingSite(name: "MYSTAKE", domain: "mystake.com"),
    GamblingSite(name: "GOBIGSLOTS", domain: "gobigslots.com"),
    GamblingSite(name: "SLOTPOWERS", domain: "slotpowers.com"),
    GamblingSite(name: "YONIBET", domain: "yonibet.com"),
    GamblingSite(name: "UNIQUE CASINO", domain: "unique-casino.com"),
    GamblingSite(name: "AGENTSPINS", domain: "agentspins.info"),
    GamblingSite(name: "KAJOT CASINO", domain: "kajot-casino.com"),
    GamblingSite(name: "FATBOSS", domain: "fatboss.com"),
    GamblingSite(name: "CASINOVOILA", domain: "casinovoila.com"),
    GamblingSite(name: "CENTAURCASINO", domain: "centaurcasino.com"),
    GamblingSite(name: "YACHTING CASINO", domain: "yachting-casino.com"),
    GamblingSite(name: "CASINOENLIGNELIVE", domain: "casinoenlignelive.com"),
    GamblingSite(name: "FOXBONUS", domain: "foxbonus.com"),
    GamblingSite(name: "CASINOMIDNIGHT", domain: "fr.casinomidnight.com"),
    GamblingSite(name: "BLACKLABELCASINO", domain: "blacklabelcasino.com"),
    GamblingSite(name: "GAMBLINGORB", domain: "gamblingorb-fr.com"),
    GamblingSite(name: "CASINOPAYANT", domain: "casinopayant.com"),
    GamblingSite(name: "ENLIGNE CASINO", domain: "enligne.casino"),
    GamblingSite(name: "VASYCASINO", domain: "vasycasino.com"),
    GamblingSite(name: "LONDONCASINO", domain: "londoncasino.com"),
    GamblingSite(name: "VEGASPLUS", domain: "vegasplus.org"),
    GamblingSite(name: "MACHANCE CASINO", domain: "machance.eu"),
    GamblingSite(name: "LUCKYBARCASINO", domain: "luckybarcasino.com"),
    GamblingSite(name: "MADNESSBONUS", domain: "madnessbonus.com"),
    GamblingSite(name: "GALLOCASINO", domain: "gallocasino.com"),
    GamblingSite(name: "CASINO60", domain: "casino60.com"),
    GamblingSite(name: "DUBLINBET", domain: "dublinbet1.com"),
    GamblingSite(name: "EVOLVECASINO", domain: "evolvecasino2.com"),
    GamblingSite(name: "JEUX CASINO ONLINE", domain: "jeux-casino-online.com"),
    GamblingSite(name: "ONLINEBINGO", domain: "onlinebingo.eu"),
    GamblingSite(name: "QBET", domain: "qbet.com"),
    GamblingSite(name: "CASINOEXTRA", domain: "casino-extra.fr"),
    GamblingSite(name: "KINGSCHANCE", domain: "kingschanceworld.com"),
    GamblingSite(name: "NODEPOSITKINGS", domain: "nodepositkings.com"),
    GamblingSite(name: "FRANCECASINO", domain: "francecasino5.com"),
    GamblingSite(name: "SLOTERMAN", domain: "sloterman.co"),
    GamblingSite(name: "MYSTAKEBONUS", domain: "mystakebonus.com"),
    GamblingSite(name: "CASINO JACKPOT", domain: "casino-jackpot.com"),
    GamblingSite(name: "PRIVILEGE CASINO", domain: "privilege-casino.com"),
    GamblingSite(name: "MEILLEURCASINO", domain: "meilleurcasino.best"),
    GamblingSite(name: "LESMACHINESASOUS", domain: "lesmachinesasous.club"),
    GamblingSite(name: "YBET", domain: "ybet.com"),
    GamblingSite(name: "1001CASINOS", domain: "1001casinos.com"),
    GamblingSite(name: "MYCASINOENLIGNE", domain: "mycasinoenligne.com"),
    GamblingSite(name: "FANTASYLEAGUE", domain: "fantasyleague.com"),
    GamblingSite(name: "MYSTAKECLUB", domain: "mystake.club"),
    GamblingSite(name: "JEUXCASINOBONUS", domain: "jeuxcasinobonus.com"),
    GamblingSite(name: "SOSCASINO", domain: "soscasino.com"),
    GamblingSite(name: "CASINOINTENSE", domain: "casino-intense.fr"),
    GamblingSite(name: "CMAXBET", domain: "cmaxbet.com"),
    GamblingSite(name: "MYSTAKEMIRROR", domain: "mystakemirror.com"),
    GamblingSite(name: "ROLLETTO", domain: "rolletto.com"),
    GamblingSite(name: "ARTCASINO", domain: "artcasino.io"),
    GamblingSite(name: "CHICKENMYSTAKE", domain: "chickenmystake.com"),
    GamblingSite(name: "PARISCASINO", domain: "pariscasino9.com"),
    GamblingSite(name: "JEUDUPOULET", domain: "jeudupoulet.com"),
    GamblingSite(name: "THORCASINO", domain: "thorcasino.io"),
    GamblingSite(name: "GREATWIN", domain: "greatwin.com"),
    GamblingSite(name: "TREASURESPINS", domain: "treasurespins.com"),
    GamblingSite(name: "BETFLIP", domain: "betflip.io"),
    GamblingSite(name: "CASINOEAGLES", domain: "casinoeagles.com"),
    GamblingSite(name: "FRESHBET", domain: "freshbet.com"),
    GamblingSite(name: "JACKPOTVILLA", domain: "jackpotvilla.com"),
    GamblingSite(name: "CAMPEONBET", domain: "campeonbet.com"),
    GamblingSite(name: "EUROPE777", domain: "europe777casino.com"),
    GamblingSite(name: "LECASINOSHOW", domain: "lecasinoshow.com"),
    GamblingSite(name: "MACAUCASINO", domain: "macaucasino4.com"),
    GamblingSite(name: "RICHKINGCASINO", domain: "richkingcasino.com"),
    GamblingSite(name: "SLOTGARD", domain: "slotgard.com"),
    GamblingSite(name: "DIVASLUCKCASINO", domain: "divasluckcasino.com"),
    GamblingSite(name: "CRAZYFORTUNECASINO", domain: "crazyfortunecasino.bet"),
    GamblingSite(name: "MYSTAKEDINO", domain: "mystakedino.com"),
    GamblingSite(name: "KRYPTOSINO", domain: "kryptosino.com"),
    GamblingSite(name: "SVENBET", domain: "svenbet.com"),
    GamblingSite(name: "1RED", domain: "1red.com"),
    GamblingSite(name: "RUBYVEGAS", domain: "rubyvegas.com"),
    GamblingSite(name: "SLOTMADNESS", domain: "slotmadness.com"),
    GamblingSite(name: "MONTECRYPTOS", domain: "montecryptos.net"),
    GamblingSite(name: "4KASINO", domain: "4kasino.com"),
    GamblingSite(name: "CASSHGRATUIT", domain: "cash-gratuit.com"),
    GamblingSite(name: "EXCELSIORCASINO", domain: "excelsior.com"),
    GamblingSite(name: "OHMYZINO", domain: "ohmyzino.com"),
    GamblingSite(name: "ROULETTE77", domain: "roulette77.fr"),
    GamblingSite(name: "STICKYWILDS", domain: "stickywilds2.com"),
    GamblingSite(name: "MYSTAKESPORTS", domain: "mystakesports.com"),
    GamblingSite(name: "CAPTAINCAZ", domain: "captaincaz.com"),
    GamblingSite(name: "BLAZE", domain: "blaze.com"),
    GamblingSite(name: "MEGAJACKPOT", domain: "lejackpot9.com"),
    GamblingSite(name: "BABELDOOR", domain: "babeldoor.com"),
    GamblingSite(name: "LUCKYTREASURE", domain: "luckytreasure.com"),
    GamblingSite(name: "AVANTGARDECASINO", domain: "avantgarde-casino.com"),
    GamblingSite(name: "MAGICALCASINO", domain: "magicalcasino.co"),
    GamblingSite(name: "PLEEEASE", domain: "pleeease.io"),
    GamblingSite(name: "JETX", domain: "jetx.casino"),
    GamblingSite(name: "7SIGNS", domain: "7signs.com"),
    GamblingSite(name: "CASINOZER", domain: "casinozer.com"),
    GamblingSite(name: "CRYPTOCASINO", domain: "crypto-casino.io"),
    GamblingSite(name: "VEGAZCASINO", domain: "vegazcasino.com"),
    GamblingSite(name: "ROYALSTARSCASINO", domain: "royalstarscasino.com"),
    GamblingSite(name: "HORUSCASINO", domain: "horuscasino.com"),
    GamblingSite(name: "PINSINO", domain: "pinsino.com"),
    GamblingSite(name: "HAZCASINO", domain: "hazcasino.com"),
    GamblingSite(name: "DATSLOTS", domain: "datslots.com"),
    GamblingSite(name: "DEPOSITWIN", domain: "depositwin.com"),
    GamblingSite(name: "MYEMPIRE", domain: "myempire.fr"),
    GamblingSite(name: "CLOUDBET", domain: "cloudbet.com"),
    GamblingSite(name: "FLAMINGCASINO", domain: "flamingcasino.com"),
    GamblingSite(name: "DUELBITS", domain: "duelbits.com"),
    GamblingSite(name: "CASINOFIZ", domain: "casinofiz.com"),
    GamblingSite(name: "BRUNOCASINO", domain: "brunocasino.com"),
    GamblingSite(name: "ATLANTISSLOTS", domain: "atlantisslots.com"),
    GamblingSite(name: "CASINOJOKA", domain: "casino-joka.net"),
    GamblingSite(name: "MOICASINO", domain: "moicasino.com"),
    GamblingSite(name: "ROYAALCASINO", domain: "royaalcasino.com"),
    GamblingSite(name: "X1CASINO", domain: "x1casino.com"),
    GamblingSite(name: "TRADITIONCASINO", domain: "casino-tradition.com"),
    GamblingSite(name: "BLUVEGAS", domain: "bluvegas.com"),
    GamblingSite(name: "LIVEBET", domain: "livebet.com"),
    GamblingSite(name: "KABOOMBET", domain: "kaboombet.casino"),
    GamblingSite(name: "BETSIO", domain: "bets.io"),
    GamblingSite(name: "LEONBET", domain: "leonbets.com"),
    GamblingSite(name: "TURBOLUCK", domain: "turboluck.com"),
    GamblingSite(name: "SCHPELL", domain: "schpell.com"),
    GamblingSite(name: "CASHIMASHI", domain: "cashimashi.com"),
    GamblingSite(name: "LUCKY31", domain: "lucky-31.com"),
    GamblingSite(name: "MRXBET", domain: "mrxbet.com"),
    GamblingSite(name: "NINECASINO", domain: "ninecasino.com"),
    GamblingSite(name: "TROPICACASINO", domain: "tropicacasino.com"),
    GamblingSite(name: "LADYLINDACASINO", domain: "ladylindacasino.com"),
    GamblingSite(name: "BLACKMAGICCASINO", domain: "blackmagiccasino.com"),
    GamblingSite(name: "COSMOBET", domain: "cosmobet.com"),
    GamblingSite(name: "WINSTLER", domain: "winstler.io"),
    GamblingSite(name: "VELOBET", domain: "velobet.com"),
    GamblingSite(name: "B7CASINO", domain: "b7casino.com"),
    GamblingSite(name: "MCASINO", domain: "mcasinofr.com"),
    GamblingSite(name: "NINBET", domain: "ninbet.com"),
    GamblingSite(name: "CRESUSCASINO", domain: "cresuscasino.com"),
    GamblingSite(name: "SPINSPIRIT", domain: "spinspirit.com"),
    GamblingSite(name: "INSTASPIN", domain: "instaspin.com"),
    GamblingSite(name: "WINOLOT", domain: "winolot.com"),
    GamblingSite(name: "FGFOX", domain: "fgfox.com"),
    GamblingSite(name: "RANTCASINO", domain: "rantcasino.com"),
    GamblingSite(name: "BETONRED", domain: "betonred.com"),
    GamblingSite(name: "TWIN", domain: "twin.com"),
    GamblingSite(name: "MEGAWINEU", domain: "megawineu.com"),
    GamblingSite(name: "JOKABET", domain: "jokabet.com"),
    GamblingSite(name: "CRYPTOLEO", domain: "cryptoleo.com"),
    GamblingSite(name: "GALAXYSPINS", domain: "galaxyspins.com"),
    GamblingSite(name: "777ONFIRE", domain: "777onfire.com"),
    GamblingSite(name: "PARTYSPINZ", domain: "partyspinz.com"),
    GamblingSite(name: "JACKBIT", domain: "jackbit.com"),
    GamblingSite(name: "BITSTARZ", domain: "bitstarz-casino.org"),
    GamblingSite(name: "TAHITICASINO", domain: "tahiticasino.com"),
    GamblingSite(name: "21GRANDCASINO", domain: "21grandcasinos.com"),
    GamblingSite(name: "CASINOVICTORIA", domain: "casino-victoria.fr"),
    GamblingSite(name: "ALEXANDERCASINO", domain: "alexandercasino.com"),
    GamblingSite(name: "SIMSINO", domain: "simsinos.com"),
    GamblingSite(name: "INSTANTCASINO", domain: "instantcasino.com"),
    GamblingSite(name: "CBET", domain: "cbet.world"),
    GamblingSite(name: "NONSTOPCASINO", domain: "nonstopcasino.co"),
    GamblingSite(name: "DEALBET", domain: "dealbet.co"),
    GamblingSite(name: "CASINOLANDIA", domain: "casinolandia.com"),
    GamblingSite(name: "CASINOCHARLES", domain: "casinocharles.co"),
    GamblingSite(name: "MADBET", domain: "madbet.eu"),
    GamblingSite(name: "DICEBOUNTY", domain: "dicebounty.com"),
    GamblingSite(name: "7BETS", domain: "7bets.io"),
    GamblingSite(name: "BETNUVO", domain: "betnuvo.com"),
    GamblingSite(name: "VOTRECASINO", domain: "votre-casino.com"),
    GamblingSite(name: "CASINODEALS", domain: "casinodeals.fr"),
    GamblingSite(name: "MYCAZCASINO", domain: "mycaz.fr"),
    GamblingSite(name: "CASINOSKY", domain: "casinosky.com"),
    GamblingSite(name: "WINNERCASINO", domain: "winnercasino.bet"),
    GamblingSite(name: "SCATTERHALL", domain: "scatterhall.com"),
    GamblingSite(name: "EFIRBET", domain: "efirbet.com"),
    GamblingSite(name: "DOCTEURCASINO", domain: "docteurcasino.io"),
    GamblingSite(name: "JEUXDCASINO", domain: "jeuxdcasino.org"),
    GamblingSite(name: "FRCASINOSPOT", domain: "frcasinospot.com"),
    GamblingSite(name: "NINEWIN", domain: "7-ninewin.com"),
    GamblingSite(name: "GITPA", domain: "gitpa.org"),
    GamblingSite(name: "BONUSFRANCE", domain: "bonusfrance.com"),
    GamblingSite(name: "7SIGNSCASINO", domain: "7signs1.com"),
    GamblingSite(name: "LOLLYBET", domain: "lolly-bet.com"),
    GamblingSite(name: "BLIZZ", domain: "blizz.io"),
    GamblingSite(name: "TRUSTDICE", domain: "trustdice.win"),
    GamblingSite(name: "PLAYREGAL", domain: "playregal.com"),
    GamblingSite(name: "CASINO1CLUB", domain: "casino1vip.com"),
    GamblingSite(name: "WOLFYCASINO", domain: "wolfycasino.com"),
    GamblingSite(name: "OCEANBREEZECASINO", domain: "oceanbreezecasino.com"),
    GamblingSite(name: "INFOCASINO", domain: "infocasino.net"),
    GamblingSite(name: "SLOTSUP", domain: "slotsup.com"),
    GamblingSite(name: "TOP10CASINOS", domain: "top10casinos.com"),
    GamblingSite(name: "BETIFY", domain: "betify.com"),
    GamblingSite(name: "CASINOENFRANCE", domain: "casinoenfrance.fr"),
    GamblingSite(name: "LESEXPERTSDUCASINO", domain: "lesexpertsducasino.com"),
    GamblingSite(name: "SANSDEPOT365", domain: "sandepot365.com"),
    GamblingSite(name: "DAGRIS", domain: "dagris.fr"),
    GamblingSite(name: "BONOBONO", domain: "bonobono.fr"),
]
// Pack essentiel : les sites légaux + les marques de casino les plus persistantes
// dans les blocages ANJ au fil des années (donc les plus répandues auprès des joueurs).
// 19 sites légaux + 31 casinos = 50, la limite technique d'Apple pour le filtrage Safari.
let essentialCasinoDomains: Set<String> = [
    "mystake.com", "vegasplus.org", "machance.eu", "unique-casino.com", "casino-extra.fr",
    "casino-intense.fr", "dublinbet1.com", "leonbets.com", "betonred.com", "kingschanceworld.com",
    "ninecasino.com", "bitstarz-casino.org", "fatboss.com", "1red.com", "cryptoleo.com",
    "greatwin.com", "rolletto.com", "thorcasino.io", "yonibet.com", "freshbet.com",
    "campeonbet.com", "playregal.com", "wolfycasino.com", "evolvecasino2.com", "lucky-31.com",
    "casinozer.com", "twin.com", "cloudbet.com", "jackbit.com", "blaze.com", "cresuscasino.com"
]
